### ISSUE TITLE
Plugin doesn't work with Foreman 1.13.0

### ISSUE THREAD

**Issue by Alucard616** [theforeman/foreman_expire_hosts#3]
This Plugin doesn't work with the new Foreman-Version 1.13.0

The error-Message i get is:
undefined method `datepicker_f' 
when i click on "new host"

or, when i select any host:
undefined method `host_expiry_warning_message' 

I assume that somethin went wrong while importing this plugin

**Comment by timogoebel** [comment]
@Alucard616 : Sorry for the delay. I released version 2.1.0 of this plugin today. The rpms should be in the repos tomorrow. This fixes compatibility with 1.13.
I'll close this issue for now, let me know if there if it does not work for you or there are more issues.
